POST http://127.0.0.1:8000/predict
Accept: application/json
Content-Type: application/json

{
  "text": "What a great MLOps lecture, I am very satisfied"
}

###

POST http://127.0.0.1:8000/predict
Accept: application/json
Content-Type: application/json

{
  "text": "The weather is terrible today."
}

###

POST http://127.0.0.1:8000/predict
Accept: application/json
Content-Type: application/json

{
  "text": "I'm watching TV."
}

###